#pragma once
#include <Windows.h>
#include <tchar.h>
#include <vector>
#include <functional>
#include <map>
#include <d3dx11.h>
#include <xnamath.h>
#include <dxerr.h>
#include "d3dx11Effect.h"
#include "Macro.h"
#include "structure.h"
#include "Utility.h"
